/**
 * Device Catalog Module
 *
 * Exports all catalog types, devices, and command codes.
 */

// Command codes
export {
  // Common codes
  LOCK_CODES,
  DISPLAY_CODES,
  DEVICE_STATE_CODES,
  // Heater codes
  HEATER_SWING_CODES,
  HEATER_H7130_SPEED_CODES,
  HEATER_SPEED_LABELS,
  HEATER_H7130_TEMP_CODES_AUTO,
  HEATER_H7130_TEMP_CODES_HEAT,
  HEATER_TEMP_MIN,
  HEATER_TEMP_MAX,
  // Heater 2 codes
  HEATER2_SWING_CODES,
  HEATER2_LOCK_CODES,
  HEATER2_SPEED_CODES,
  HEATER2_SPEED_LABELS,
  HEATER2_TEMP_CODES_AUTO,
  HEATER2_TEMP_CODES_AUTO_TURN,
  // Fan codes
  FAN_SWING_CODES,
  FAN_H7102_SPEED_CODES,
  FAN_SPEED_STEP,
  // Humidifier codes
  HUMIDIFIER_H7140_SPEED_CODES,
  HUMIDIFIER_H7142_SPEED_CODES,
  HUMIDIFIER_H7142_UV_ON,
  // Kettle codes
  KETTLE_MODE_CODES,
  // Ice maker codes
  ICE_MAKER_CODES,
  // Purifier codes
  PURIFIER_H7120_SPEED_CODES,
  PURIFIER_H7120_NIGHT_LIGHT_CODES,
  PURIFIER_H7122_SPEED_CODES,
  PURIFIER_H7126_SPEED_CODES,
  // Labels
  AIR_QUALITY_LABELS,
  PURIFIER_SPEED_COMMAND_MAP,
  // Debounce constants
  DEBOUNCE_BRIGHTNESS_MS,
  DEBOUNCE_COLOR_MS,
  KETTLE_MODE_DELAY_MS,
  // Helpers
  getAirQualityFromPM25,
  getAirQualityLabelFromPM25,
} from './commands.js';
